apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: llm-tutor
data:
  DB_PORT: "5433"              
  # Redis externo (n√£o instalar no cluster)
  REDIS_ENDPOINT: "redis-10279.c56.east-us.azure.cloud.redislabs.com"
  REDIS_PORT: "10279"                
  # RabbitMQ externo
  RABBITMQ_URL: "amqp://appuser:apppass@rabbitmq:5672/%2F"
  RABBITMQ_EXCHANGE: "app.events"
  RABBITMQ_ROUTING_KEY: "quiz.generate.request"
  RABBITMQ_PREFETCH: "16"
