apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: quiz-generator-so
  namespace: llm-tutor
spec:
  scaleTargetRef:
    name: quiz-generator-consumer
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 10
  cooldownPeriod: 60
  triggers:
    - type: rabbitmq
      metadata:
        queueName: quiz.create.q
        mode: QueueLength
        value: "50"
        activationThreshold: "1"
      authenticationRef:
        name: rabbitmq-auth


