apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: evaluation-service-so
  namespace: llm-tutor
spec:
  scaleTargetRef:
    name: evaluation-service
  minReplicaCount: 2
  maxReplicaCount: 10
  pollingInterval: 10
  cooldownPeriod: 60
  triggers:
    - type: rabbitmq
      metadata:
        queueName: quiz.generate.q
        mode: QueueLength
        value: "50"
        activationThreshold: "1"
      authenticationRef:
        name: rabbitmq-auth
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 120
          policies:
            - type: Percent
              value: 50
              periodSeconds: 60


